name: Deploy on Netlify

# Evénements qui déclenchent le workflow : triggers
# Ici le workflow se déclanche sur chaque push de la branche main ou sur un déclenchement manuel
on:
  push:
    branches:
      - main
  workflow_dispatch:

# On défini des permissions pour autoriser le déploiement sur GitHub Pages
# copié collé de la doc, obligatoire pour que ça marche
permissions:
  contents: read
  pages: write
  id-token: write

# on authorise un seul groupe de jobs à la fois
concurrency:
  # Le nom du groupe de jobs
  group: "pages"
  # on ne veut pas que les jobs soient annulés si un autre est en cours
  cancel-in-progress: false

jobs: 

  build-and-deploy:
    runs-on: ubuntu-latest
    # on pense à préciser le working-directory pour que les actions se fassent dans dossier frontend
    defaults:
      run:
        working-directory: frontend

    steps: 
      # on récupère le code
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      # on installe Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4

      # on installe les dépendances
      - name: 📦 Install dependencies
        run: npm install

      # Autres jobs (tests, biome…)

      # on build notre code
      - name: 🏗️ Build the project
        run: npm run build

      # Install de la CLI netlify en local (dans la doc ils recommandent de ne pas l'installer en global)
      # https://docs.netlify.com/cli/get-started/#installation-in-a-ci-environment
      - name: Install Netlify CLI
        #run: npm install netlify-cli --save-dev
        run: npm install netlify-cli -g

      # Deploy to Netlify
      - name: 🚀 Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        # on fournit direct le dossier à deployer et on précise que c'est pour la prod
        run: netlify deploy --prod --dir=dist --site ${{ secrets.NETLIFY_SITE_ID }}

